### PR TITLE
Shifted the indicator to left side

### LINKED ISSUE #52: [bug]: sub menu indication line should be on left side
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we generate demo test cases data, the UI shows the active submenu-item indicator on the right side which ideally should be on the left side.

### Steps to reproduce

1. Go to the home page of the Keploy UI.
2. Go to the test lists page from the side menu.
3. See the behavior in the submenu.

image
if we put the indicator on the left side it would look better.

### Environment

_No response_

### Version

Local

### LINKED ISSUE #368: [bug]: sub menu indication line should be on left side
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we generate demo test cases data, the UI shows the active submenu-item indicator on the right side which ideally should be on the left side.

### Steps to reproduce

1. Go to the home page of the Keploy UI.
2. Go to the test lists page from the side menu.
3. See the behavior in the submenu.

image
if we put the indicator on the left side it would look better.

### Environment

_No response_

### Version

Local

### PR DESCRIPTION
**Pull request by Janvi-Thakkar**
# Pull Request Template
Shifted active tab indicator to left side in the mini navbar.

Fixes keploy/keploy#368 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Janvi-Thakkar** [comment]
@nehagup can you please review this?

**Comment by nehagup** [comment]
@Janvi-Thakkar Thanks for the PR. I shall review it soon :)

**Comment by nehagup** [comment]
@Janvi-Thakkar Have you pushed all the changes, because this isn't working right now. :) 
Screenshot 2022-05-13 at 12 36 20 AM

**Comment by Janvi-Thakkar** [comment]
> @Janvi-Thakkar Have you pushed all the changes, because this isn't working right now. :) Screenshot 2022-05-13 at 12 36 20 AM

Yes ma'am, I have pushed all necessary files. This is the current state of UI in my machine:
image

**Comment by nehagup** [comment]
@anirudhjain75 can you please review this PR? I believe we can directly override mui tab-indicator class and will not require to make changes to span.

**Comment by nehagup** [comment]
@anirudhjain75  can you please review this PR? I believe we can directly override mui tab-indicator class and will not require to make changes to span.

**Comment by anirudhjain75** [comment]
Hi @Janvi-Thakkar . Just removing span and only using `.MuiTabs-indicator` in the css file, also does the job. The better way to style would be created a styled component of mui component and using that inplace of vanilla component. https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component Here is a link incase you'd like to know more about customizing component using mui `styled` API.

**Comment by nehagup** [comment]
Thanks @anirudhjain75 IMO using styled API would be more apt in this case. @Janvi-Thakkar what do you think?

**Comment by Janvi-Thakkar** [comment]
> Thanks @anirudhjain75 IMO using styled API would be more apt in this case. @Janvi-Thakkar what do you think?

@nehagup I have to check the styled API for that. Will tell you about my view after checking it.

**Comment by Janvi-Thakkar** [comment]
> Hi @Janvi-Thakkar . Just removing span and only using `.MuiTabs-indicator` in the css file, also does the job. The better way to style would be created a styled component of mui component and using that inplace of vanilla component. https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component Here is a link incase you'd like to know more about customizing component using mui `styled` API.
> 
> @nehagup What do you think we should follow in this case ?. Just overriding the css make its quicker to do but using `styled` API helps keep information like styling within the component which might help keep the structure independent.

@anirudhjain75 Thank You for the suggestions. Will check this:)

**Comment by nehagup** [comment]
@Janvi-Thakkar are you still working on this?

**Comment by Janvi-Thakkar** [comment]
> @Janvi-Thakkar are you still working on this?

Sorry, I could not update this in past some days. I would commit the suggested changes soon:)

**Comment by nehagup** [comment]
@Janvi-Thakkar are you still working on this?

**Pull request closed without merging**
