### PR TITLE
Add. Appswitcher hamburger menu in test cases page

### LINKED ISSUE #77: [feature]: Add a hamburger button for applications under test cases
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

When we navigate to the test cases section at keploy server, the applications tested are listed on the left (here-superhero-api). We can add a hamburger button to hide and show them as per user's convenience like the one done for Test cases and Test runs.

Screenshot from 2022-10-05 15-28-14

### Why should this be worked on?

This feature will make the UI more responsive

### PR DESCRIPTION
**Pull request by titanventura**
### Summary:
Added hamburger menu to test case list page.

Fixes #77 

## Type of change
- [x] New feature (non-breaking change which adds functionality).

## How Has This Been Tested?
Tests Ran : Since the frontend repo does not have any automated tests, I had verified this by testing the feature manually by running the frontend code and it works.

## Additional Context (Please include any Screenshots/gifs if relevant)

Collapsed state
image

Expanded state
image

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by nehagup — CHANGES_REQUESTED** [review]
@titanventura the UI is breaking with these changes. Switching application is not changing the url parameter. Also, after clicking on application test cases clicking on test run page is not leading to the same. 

I checked the same with `main` branch and it's working fine.

**Comment by nehagup** [comment]
I've resolved the merge conflict here - https://github.com/keploy/ui/tree/titanventura-main

**Comment by titanventura** [comment]
@nehagup I have made the changes requested. Please feel free to review them !

**Comment by nehagup** [comment]
@titanventura can you please sign the DCO?

**Comment by titanventura** [comment]
@nehagup, Have signed the DCO ! Please do review. Thank you so much ! Got to learn a lot !

**Comment by titanventura** [comment]
@nehagup , any updates on this ? it was the only PR i opened for hacktoberfest !! Would have been great if it was merged before Oct 31st 😞

**Review by nehagup — APPROVED** [review]
LGTM! Thanks for the contribution and apologies for the delay. 👏

**Comment by titanventura** [comment]
Hey no probs @nehagup, thank you so much for taking the time to review and merge
Cheers ! 🚀

**Pull request merged**
